// MIT License - Copyright (c) 2026 wallstop
// Full license text: https://github.com/wallstop/unity-helpers/blob/main/LICENSE

namespace WallstopStudios.UnityHelpers.Tests.Serialization
{
    using System;
    using System.Collections.Generic;
    using NUnit.Framework;
    using WallstopStudios.UnityHelpers.Core.Serialization.WallstopProto;

    /// <summary>
    /// Pins the proto3 schema text against the wire shapes the formatters actually write.
    /// </summary>
    public sealed class WProtoSchemaTextTests
    {
        private const string GeneratedHeader =
            "// Generated by Wallstop Studios Unity Helpers. Do not edit; regenerate instead.\n"
            + "syntax = \"proto3\";\n";

        [Test]
        public void SimpleContractRendersTheFullSchemaText()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaPoint) },
                "test.pkg",
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered, "A contract type must render.");
            Assert.AreEqual(
                GeneratedHeader
                    + "package test.pkg;\n"
                    + "\n"
                    + "message SchemaPoint {\n"
                    + "  int32 X = 1;\n"
                    + "  int32 Y = 2;\n"
                    + "}\n"
                    + "\n",
                schema,
                "The schema is generated output; its exact text is the contract."
            );
            Assert.IsEmpty(diagnostics, "A fully supported contract must not report anything.");
        }

        [Test]
        public void ScalarMembersMapToTheirWireTypes()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaScalars) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> _
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains(
                "sint64 ZigZagValue = 1;",
                schema,
                "DataFormat.ZigZag renders sint."
            );
            StringAssert.Contains("int32 Signed = 2;", schema);
            StringAssert.Contains("uint32 Unsigned = 3;", schema);
            StringAssert.Contains("fixed64 DoubleValue = 4;", schema);
            StringAssert.Contains("fixed32 FloatValue = 5;", schema);
            StringAssert.Contains("string Name = 6;", schema);
            StringAssert.Contains(
                "bytes Payload = 7;",
                schema,
                "A byte[] member is bytes, not a run."
            );
            StringAssert.Contains("uint32 Initial = 8;", schema, "A char member rides a varint.");
            StringAssert.Contains("bool Flag = 9;", schema);
            StringAssert.Contains(
                "optional int32 Maybe = 10;",
                schema,
                "Nullable presence is explicit."
            );
        }

        [Test]
        public void BclValueMembersRenderAsTheirMessageShapes()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaBcl) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> _
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains("BclGuid Id = 1;", schema);
            StringAssert.Contains("BclDateTime Moment = 2;", schema);
            StringAssert.Contains("BclTimeSpan Duration = 3;", schema);
            StringAssert.Contains("BclDecimal Amount = 4;", schema);
            StringAssert.Contains("BclUri Source = 5;", schema);
            StringAssert.Contains(
                "message BclGuid {\n  fixed64 low = 1;\n  fixed64 high = 2;\n}",
                schema
            );
            StringAssert.Contains(
                "message BclDateTime {\n  sint64 value = 1;\n  uint32 scale = 2;\n}",
                schema
            );
        }

        [Test]
        public void CollectionShapesMatchTheGeneratorWrappers()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaCollections) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> _
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains(
                "message RowsEntry {\n  repeated int32 values = 1;\n}",
                schema,
                "A jagged array becomes the wrapper message the generator synthesizes."
            );
            StringAssert.Contains("repeated RowsEntry Rows = 1;", schema);
            StringAssert.Contains(
                "repeated bytes Blobs = 2;",
                schema,
                "byte[][] is repeated bytes, not a wrapper."
            );
            StringAssert.Contains(
                "message GridRect {\n  repeated int32 dims = 1;\n  repeated int32 values = 2;\n}",
                schema,
                "A rectangular array becomes the dims/values wrapper."
            );
            StringAssert.Contains("GridRect Grid = 3;", schema);
            StringAssert.Contains("map<string, int32> Counts = 4;", schema);
            StringAssert.Contains("repeated SchemaPoint Points = 5;", schema);
        }

        [Test]
        public void NonScalarMapKeyBecomesAnEntryMessage()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaEnumMap) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> _
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains("map<string, int32> ByString = 1;", schema);
            StringAssert.Contains(
                "message ByColorEntry {\n  SchemaColor key = 1;\n  int32 value = 2;\n}",
                schema,
                "proto3 map keys are scalars only; the wire form is the entry message either way."
            );
            StringAssert.Contains("repeated ByColorEntry ByColor = 2;", schema);
            StringAssert.Contains("enum SchemaColor {", schema);
            StringAssert.Contains("None = 0;", schema);
        }

        [Test]
        public void IncludesEmitTheSubtypeWithItsMembersAheadOfTheBase()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaIncludeBase) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains("int32 Extra = 10;", schema);
            StringAssert.Contains("int32 BaseId = 1;", schema);
            StringAssert.Contains("string BaseName = 2;", schema);
            StringAssert.Contains("SchemaDerived schemaDerived = 7;", schema);
            StringAssert.Contains(
                "// SchemaIncludeBase writes this subtype under tag 7: its own members first, then the base's.",
                schema
            );
            int derivedIndex = schema.IndexOf("message SchemaDerived {", StringComparison.Ordinal);
            Assert.Greater(derivedIndex, 0, "The include renders the subtype as its own message.");
            Assert.IsEmpty(diagnostics);
        }

        [Test]
        public void EnumOdditiesAreReportedRatherThanSilentlyRendered()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaEnumHost) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains(
                "option allow_alias = true;",
                schema,
                "Aliased enum values need the proto3 option."
            );
            Assert.AreEqual(
                1,
                diagnostics.Count,
                "Only the missing zero reports; aliases are handled."
            );
            StringAssert.Contains("opens at 1", diagnostics[0]);
        }

        [Test]
        public void RenderingTheSameInputTwiceIsDeterministic()
        {
            WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaCollections), typeof(SchemaScalars) },
                "demo",
                null,
                out string first,
                out IReadOnlyList<string> _
            );
            WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaCollections), typeof(SchemaScalars) },
                "demo",
                null,
                out string second,
                out IReadOnlyList<string> _
            );

            Assert.AreEqual(
                first,
                second,
                "A schema a consumer diffs must not shuffle between runs."
            );
        }

        [Test]
        public void NonContractAndGenericTypeInputsAreIgnored()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(string), typeof(Action<>) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> _
            );

            Assert.IsFalse(rendered, "Nothing renderable means no schema.");
            Assert.IsTrue(schema == null);
        }
    }

    [WProtoContract]
    public sealed partial class SchemaPoint
    {
        [WProtoMember(1)]
        public int X;

        [WProtoMember(2)]
        public int Y;
    }

    [WProtoContract]
    public sealed partial class SchemaScalars
    {
        [WProtoMember(1, DataFormat = WProtoDataFormat.ZigZag)]
        public long ZigZagValue;

        [WProtoMember(2)]
        public int Signed;

        [WProtoMember(3)]
        public uint Unsigned;

        [WProtoMember(4)]
        public double DoubleValue;

        [WProtoMember(5)]
        public float FloatValue;

        [WProtoMember(6)]
        public string Name;

        [WProtoMember(7)]
        public byte[] Payload;

        [WProtoMember(8)]
        public char Initial;

        [WProtoMember(9)]
        public bool Flag;

        [WProtoMember(10)]
        public int? Maybe;
    }

    [WProtoContract]
    public sealed partial class SchemaBcl
    {
        [WProtoMember(1)]
        public Guid Id;

        [WProtoMember(2)]
        public DateTime Moment;

        [WProtoMember(3)]
        public TimeSpan Duration;

        [WProtoMember(4)]
        public decimal Amount;

        [WProtoMember(5)]
        public Uri Source;
    }

    [WProtoContract]
    public sealed partial class SchemaCollections
    {
        [WProtoMember(1)]
        public int[][] Rows;

        [WProtoMember(2)]
        public byte[][] Blobs;

        [WProtoMember(3)]
        public int[,] Grid;

        [WProtoMember(4)]
        public Dictionary<string, int> Counts;

        [WProtoMember(5)]
        public List<SchemaPoint> Points;
    }

    public enum SchemaColor
    {
        None = 0,
        Red = 1,
        Blue = 2,
    }

    [WProtoContract]
    public sealed partial class SchemaEnumMap
    {
        [WProtoMember(1)]
        public Dictionary<string, int> ByString;

        [WProtoMember(2)]
        public Dictionary<SchemaColor, int> ByColor;
    }

    [WProtoContract]
    [WProtoInclude(7, typeof(SchemaDerived))]
    public partial class SchemaIncludeBase
    {
        [WProtoMember(1)]
        public int BaseId;

        [WProtoMember(2)]
        public string BaseName;
    }

    [WProtoContract]
    public sealed partial class SchemaDerived : SchemaIncludeBase
    {
        [WProtoMember(10)]
        public int Extra;
    }

    public enum SchemaAliased
    {
        First = 1,
        Prime = 1,
        Second = 2,
    }

    [WProtoContract]
    public sealed partial class SchemaEnumHost
    {
        [WProtoMember(1)]
        public SchemaAliased Value;
    }
}
