// MIT License - Copyright (c) 2026 wallstop
// Full license text: https://github.com/wallstop/unity-helpers/blob/main/LICENSE

namespace WallstopStudios.UnityHelpers.Proto.Generator
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp;
    using Microsoft.CodeAnalysis.CSharp.Syntax;

    internal static class ExternalProviderRegistrations
    {
        private const string ModelName = "ProtoBuf.Meta.RuntimeTypeModel";
        private const string SerializerName = "ProtoBuf.Serializers.ISerializer<T>";
        private const string ProxyName = "ProtoBuf.Serializers.ISerializerProxy<T>";

        internal static bool Emit(
            GeneratorExecutionContext context,
            IEnumerable<TypeDeclarationSyntax> declarations,
            bool disableModuleInitializer
        )
        {
            INamedTypeSymbol model = context.Compilation.GetTypeByMetadataName(ModelName);
            if (
                model == null
                || !context.Compilation.IsSymbolAccessibleWithin(
                    model,
                    context.Compilation.Assembly
                )
                || !HasApi(model, "RegisterExternalSerializer")
                || !HasApi(model, "RegisterNullableExternalSerializer")
            )
            {
                return false;
            }
            foreach (SyntaxTree tree in context.Compilation.SyntaxTrees)
            {
                if (tree.Options is CSharpParseOptions options)
                {
                    foreach (string symbol in options.PreprocessorSymbolNames)
                    {
                        if (string.Equals(symbol, "WALLSTOP_PROTO_ONLY", StringComparison.Ordinal))
                        {
                            return false;
                        }
                    }
                }
            }
            SortedSet<string> registrations = new SortedSet<string>(StringComparer.Ordinal);
            HashSet<ISymbol> seen = new HashSet<ISymbol>(SymbolEqualityComparer.Default);
            foreach (TypeDeclarationSyntax declaration in declarations)
            {
                SemanticModel semantics = context.Compilation.GetSemanticModel(
                    declaration.SyntaxTree
                );
                INamedTypeSymbol provider =
                    semantics.GetDeclaredSymbol(declaration) as INamedTypeSymbol;
                if (
                    provider == null
                    || !seen.Add(provider)
                    || provider.TypeKind != TypeKind.Class
                    || provider.IsAbstract
                    || provider.IsStatic
                    || TypeNaming.IsOpen(provider)
                    || !TypeNaming.IsNameable(provider, context.Compilation)
                )
                {
                    continue;
                }
                foreach (INamedTypeSymbol contract in provider.AllInterfaces)
                {
                    string name = contract.OriginalDefinition.ToDisplayString();
                    if (
                        !string.Equals(name, SerializerName, StringComparison.Ordinal)
                        && !string.Equals(name, ProxyName, StringComparison.Ordinal)
                    )
                    {
                        continue;
                    }
                    ITypeSymbol target = contract.TypeArguments[0];
                    if (
                        TypeNaming.IsOpen(target)
                        || !TypeNaming.IsNameable(target, context.Compilation)
                    )
                    {
                        continue;
                    }
                    bool nullable =
                        target is INamedTypeSymbol named
                        && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
                    string method =
                        target.IsValueType && !nullable
                            ? "RegisterNullableExternalSerializer"
                            : "RegisterExternalSerializer";
                    registrations.Add(
                        "global::"
                            + ModelName
                            + "."
                            + method
                            + "<"
                            + provider.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                            + ", "
                            + target.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                            + ">();"
                    );
                }
            }
            if (registrations.Count == 0)
            {
                return false;
            }
            StringBuilder source = new StringBuilder();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("#if !WALLSTOP_PROTO_ONLY");
            source.AppendLine("namespace WallstopStudios.UnityHelpers.Generated");
            source.AppendLine("{");
            source.AppendLine("    internal static class LegacyExternalProviderRegistrar");
            source.AppendLine("    {");
            source.AppendLine("#if UNITY_5_3_OR_NEWER");
            source.AppendLine("#if UNITY_EDITOR");
            source.AppendLine("        [global::UnityEditor.InitializeOnLoadMethod]");
            source.AppendLine("#endif");
            source.AppendLine(
                "        [global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]"
            );
            source.AppendLine("#else");
            if (!disableModuleInitializer)
            {
                source.AppendLine(
                    "        [global::System.Runtime.CompilerServices.ModuleInitializer]"
                );
            }
            source.AppendLine("#endif");
            source.AppendLine("        internal static void Register()");
            source.AppendLine("        {");
            foreach (string registration in registrations)
            {
                source.AppendLine("            " + registration);
            }
            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            source.AppendLine("#endif");
            context.AddSource("LegacyExternalProviderRegistrar.g.cs", source.ToString());
            return true;
        }

        private static bool HasApi(INamedTypeSymbol model, string name)
        {
            if (model == null)
            {
                return false;
            }
            foreach (ISymbol member in model.GetMembers(name))
            {
                if (
                    member is IMethodSymbol method
                    && method.IsStatic
                    && method.Arity == 2
                    && method.Parameters.Length == 0
                    && method.ReturnsVoid
                    && method.DeclaredAccessibility == Accessibility.Public
                    && method.TypeParameters[0].HasReferenceTypeConstraint
                    && method.TypeParameters[0].ConstraintTypes.Length == 0
                    && !method.TypeParameters[0].HasConstructorConstraint
                    && method.TypeParameters[1].ConstraintTypes.Length == 0
                    && !method.TypeParameters[1].HasConstructorConstraint
                    && !method.TypeParameters[1].HasReferenceTypeConstraint
                    && !method.TypeParameters[1].HasUnmanagedTypeConstraint
                    && method.TypeParameters[1].HasValueTypeConstraint
                        == (
                            string.Equals(
                                name,
                                "RegisterNullableExternalSerializer",
                                StringComparison.Ordinal
                            )
                        )
                )
                {
                    return true;
                }
            }
            return false;
        }
    }
}
