// MIT License - Copyright (c) 2026 wallstop
// Full license text: https://github.com/wallstop/unity-helpers/blob/main/LICENSE

namespace WallstopStudios.UnityHelpers.Core.Serialization.WallstopProto
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Globalization;
    using System.Linq;
    using System.Reflection;
    using System.Text;

    /// <summary>
    /// Renders the wire contract of <see cref="WProtoContractAttribute"/> types as a proto3 schema a
    /// downstream consumer can read with any protobuf toolchain.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Every declaration emitted here is chosen to be byte-exact with what the formatters write:
    /// scalars map to their wire types, jagged collections map to the same wrapper messages the
    /// source generator synthesizes, rectangular arrays map to the <c>dims</c>/<c>values</c> wrapper
    /// from <see cref="WProtoRectangular"/>, maps map to proto3 <c>map</c> entries (or an explicit
    /// entry message where the key has no proto3 spelling), and a
    /// <see cref="WProtoIncludeAttribute"/> subtype is emitted as a message holding the subtype's
    /// members followed by the base's, exactly as the wire lays the bytes out. The BCL value types
    /// the formatters serve (<see cref="DateTime"/>, <see cref="TimeSpan"/>, <see cref="Guid"/>,
    /// <see cref="decimal"/>, <see cref="Uri"/>) are emitted as the message shapes those formatters
    /// actually write, which replicate protobuf-net's <c>.bcl.*</c> conventions.
    /// </para>
    /// <para>
    /// Two writer behaviors have no proto3 spelling and are deliberately not reflected in the
    /// schema: <see cref="WProtoMemberAttribute.IsRequired"/>, which changes only whether a default
    /// value is written, and the never-packed rule for <see cref="char"/> runs, which changes only
    /// whether runs are compressed. Neither changes a field's number or type, so a schema consumer
    /// decodes both correctly without knowing them.
    /// </para>
    /// <para>
    /// Nothing here throws on a shape it cannot express. An unsupported member is skipped and
    /// reported through the returned diagnostics, so the rest of the schema stays usable; a caller
    /// that requires every member represented checks that the diagnostics list is empty.
    /// </para>
    /// </remarks>
    public static class WProtoSchemaText
    {
        private const string Header =
            "// Generated by Wallstop Studios Unity Helpers. Do not edit; regenerate instead.\n"
            + "syntax = \"proto3\";\n";

        /// <summary>
        /// The BCL value types this toolchain serves on the wire, mapped to the message shapes the
        /// formatters actually write.
        /// </summary>
        private static readonly Dictionary<
            Type,
            (string MessageName, string Definition)
        > BclMessageShapes = new Dictionary<Type, (string, string)>
        {
            {
                typeof(DateTime),
                (
                    "BclDateTime",
                    "// Replicates protobuf-net's .bcl.DateTime layout.\n"
                        + "message BclDateTime {\n"
                        + "  sint64 value = 1;\n"
                        + "  uint32 scale = 2;\n"
                        + "}"
                )
            },
            {
                typeof(TimeSpan),
                (
                    "BclTimeSpan",
                    "// Replicates protobuf-net's .bcl.TimeSpan layout.\n"
                        + "message BclTimeSpan {\n"
                        + "  sint64 value = 1;\n"
                        + "  uint32 scale = 2;\n"
                        + "}"
                )
            },
            {
                typeof(Guid),
                (
                    "BclGuid",
                    "// Replicates protobuf-net's .bcl.Guid layout: two fixed-64 halves in\n"
                        + "// Guid.ToByteArray order; an all-zero Guid writes an empty message.\n"
                        + "message BclGuid {\n"
                        + "  fixed64 low = 1;\n"
                        + "  fixed64 high = 2;\n"
                        + "}"
                )
            },
            {
                typeof(decimal),
                (
                    "BclDecimal",
                    "// Replicates protobuf-net's .bcl.Decimal layout.\n"
                        + "message BclDecimal {\n"
                        + "  uint64 low = 1;\n"
                        + "  uint32 high = 2;\n"
                        + "  uint32 sign_scale = 3;\n"
                        + "}"
                )
            },
            {
                typeof(Uri),
                (
                    "BclUri",
                    "// Replicates protobuf-net's .bcl.Uri layout: the UTF-8 original string.\n"
                        + "message BclUri {\n"
                        + "  string original_string = 1;\n"
                        + "}"
                )
            },
        };

        /// <summary>
        /// The types this toolchain refuses to place on the wire, with the recorded reason.
        /// </summary>
        private static readonly Dictionary<Type, string> RefusedTypes = new Dictionary<Type, string>
        {
            {
                typeof(DateTimeOffset),
                "neither supported protobuf-net version provides any wire shape for it"
            },
            { typeof(IntPtr), "platform-width pointer; protobuf-net 2.x has no serializer for it" },
            {
                typeof(UIntPtr),
                "platform-width pointer; protobuf-net 2.x has no serializer for it"
            },
            { typeof(Type), "bytes name a runtime-bound type another process cannot resolve" },
        };

        /// <summary>
        /// Renders a proto3 schema for the given contract types.
        /// </summary>
        /// <param name="contractTypes">
        /// The <see cref="WProtoContractAttribute"/> types to render. Types without the attribute are
        /// ignored; types referenced as members render only when listed here or reached through an
        /// include or an element mapping.
        /// </param>
        /// <param name="packageName">The proto package clause, or <c>null</c> to omit it.</param>
        /// <param name="surrogates">
        /// The <see cref="WProtoSurrogateAttribute"/> pairs to honor, keyed by the real type.
        /// Members whose type is replaced by a surrogate render as the surrogate's message.
        /// </param>
        /// <param name="schema">The rendered schema, or <c>null</c> when nothing was rendered.</param>
        /// <param name="diagnostics">
        /// Every skipped member and naming adjustment the caller may need to act on. Empty when the
        /// schema expresses every member of every rendered contract.
        /// </param>
        /// <returns><c>true</c> when at least one contract was rendered.</returns>
        public static bool TryWriteSchema(
            IEnumerable<Type> contractTypes,
            string packageName,
            IReadOnlyDictionary<Type, Type> surrogates,
            out string schema,
            out IReadOnlyList<string> diagnostics
        )
        {
            schema = null;
            diagnostics = Array.Empty<string>();

            if (contractTypes == null)
            {
                return false;
            }

            SchemaBuilder builder = new SchemaBuilder(surrogates);
            foreach (Type contractType in contractTypes)
            {
                if (contractType == null || contractType.IsGenericTypeDefinition)
                {
                    continue;
                }

                builder.TryAddContract(contractType);
            }

            if (builder.MessageCount == 0)
            {
                return false;
            }

            schema = builder.Render(packageName);
            diagnostics = builder.Diagnostics.ToArray();
            return true;
        }

        private sealed class SchemaBuilder
        {
            private const BindingFlags MemberSearchFlags =
                BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;
            private const string MessageKeyPrefix = "message ";
            private const string EnumKeyPrefix = "enum ";

            private readonly IReadOnlyDictionary<Type, Type> _surrogates;
            private readonly List<string> _diagnostics = new List<string>();
            private readonly Dictionary<string, string> _blocks = new Dictionary<string, string>(
                StringComparer.Ordinal
            );
            private readonly HashSet<Type> _rendered = new HashSet<Type>();
            private readonly HashSet<string> _usedNames = new HashSet<string>(
                StringComparer.Ordinal
            );

            public SchemaBuilder(IReadOnlyDictionary<Type, Type> surrogates)
            {
                _surrogates = surrogates ?? new Dictionary<Type, Type>();
            }

            public List<string> Diagnostics => _diagnostics;

            public int MessageCount => _rendered.Count;

            public string TryAddContract(Type contractType)
            {
                if (_rendered.Contains(contractType))
                {
                    return SchemaNameOf(contractType);
                }

                object[] contractMarkers = contractType.GetCustomAttributes(
                    typeof(WProtoContractAttribute),
                    false
                );
                if (contractMarkers.Length == 0)
                {
                    return null;
                }

                _rendered.Add(contractType);
                string messageName = NextName(
                    ResolveSchemaName(contractType, (WProtoContractAttribute)contractMarkers[0])
                );
                _contractNames[contractType] = messageName;

                List<IncludeEntry> includes = CollectIncludes(contractType);
                List<MemberEntry> members = CollectMembers(contractType, messageName);
                StringBuilder body = new StringBuilder();
                body.Append("message ").Append(messageName).Append(" {").Append("\n");
                foreach (MemberEntry member in members)
                {
                    string line = RenderField(messageName, member);
                    if (line != null)
                    {
                        body.Append("  ").Append(line).Append("\n");
                    }
                }

                foreach (IncludeEntry include in includes)
                {
                    body.Append("  // Subtype tag ")
                        .Append(include.Tag.ToString(CultureInfo.InvariantCulture))
                        .Append(" carries the whole ")
                        .Append(include.SchemaName)
                        .Append(" message on the wire.")
                        .Append("\n");
                    body.Append("  ")
                        .Append(include.SchemaName)
                        .Append(' ')
                        .Append(FieldName(include.SchemaName))
                        .Append(" = ")
                        .Append(include.Tag.ToString(CultureInfo.InvariantCulture))
                        .Append(";")
                        .Append("\n");
                }

                body.Append("}");
                _blocks[MessageKeyPrefix + messageName] = body.ToString();
                return messageName;
            }

            private readonly Dictionary<Type, string> _contractNames =
                new Dictionary<Type, string>();

            private string RenderField(string ownerName, MemberEntry member)
            {
                Type memberType = member.MemberType;

                if (RefusedTypes.TryGetValue(memberType, out string refusal))
                {
                    _diagnostics.Add(
                        $"{ownerName}.{member.SchemaName}: {memberType.Name} refused -- {refusal}; skipped."
                    );
                    return null;
                }

                if (
                    memberType.IsGenericType
                    && memberType.GetGenericTypeDefinition() == typeof(Nullable<>)
                )
                {
                    Type underlying = memberType.GetGenericArguments()[0];
                    if (!TryMapElement(underlying, member, out string nullableType))
                    {
                        _diagnostics.Add(
                            $"{ownerName}.{member.SchemaName}: Nullable<{underlying.Name}> of an unsupported element skipped."
                        );
                        return null;
                    }

                    return $"optional {nullableType} {member.SchemaName} = {member.Tag};";
                }

                if (TryMapScalar(memberType, member, out string scalarType))
                {
                    return $"{scalarType} {member.SchemaName} = {member.Tag};";
                }

                if (memberType == typeof(byte[]))
                {
                    return $"bytes {member.SchemaName} = {member.Tag};";
                }

                if (memberType.IsEnum)
                {
                    string enumName = TryAddEnum(memberType);
                    return enumName == null
                        ? null
                        : $"{enumName} {member.SchemaName} = {member.Tag};";
                }

                if (memberType.IsArray && memberType.GetArrayRank() > 1)
                {
                    // A rectangular array travels as the dims/values wrapper; see WProtoRectangular
                    // for the read-side shape validation.
                    Type elementType = memberType.GetElementType();
                    string rectName = NextName(member.SchemaName + "Rect");
                    if (
                        !TryBuildRectBody(
                            rectName,
                            elementType,
                            ownerName,
                            out string rectDefinition
                        )
                    )
                    {
                        return null;
                    }

                    _blocks[MessageKeyPrefix + rectName] =
                        "// Rectangular-array wrapper; see WProtoRectangular: the dimension\n"
                        + "// product must equal the delivered element count.\n"
                        + rectDefinition;
                    return $"{rectName} {member.SchemaName} = {member.Tag};";
                }

                object[] contractMarkers = memberType.GetCustomAttributes(
                    typeof(WProtoContractAttribute),
                    false
                );
                if (contractMarkers.Length > 0)
                {
                    string contractName = TryAddContract(memberType);
                    return $"{contractName} {member.SchemaName} = {member.Tag};";
                }

                if (TryResolveSurrogate(memberType, out Type surrogateType))
                {
                    string surrogateName = TryAddContract(surrogateType);
                    if (surrogateName != null)
                    {
                        return $"{surrogateName} {member.SchemaName} = {member.Tag};";
                    }
                }

                if (TryShapeRepeated(memberType, member, ownerName, out string repeatedType))
                {
                    return $"repeated {repeatedType} {member.SchemaName} = {member.Tag};";
                }

                _diagnostics.Add(
                    $"{ownerName}.{member.SchemaName}: {memberType.Name} has no WProto contract and no supported wire shape; skipped."
                );
                return null;
            }

            private bool TryShapeRepeated(
                Type memberType,
                MemberEntry member,
                string ownerName,
                out string repeatedType
            )
            {
                repeatedType = null;

                if (memberType.IsGenericType && IsMapDictionary(memberType))
                {
                    return TryBuildMap(memberType, member, ownerName, out repeatedType);
                }

                Type elementType = GetElementType(memberType);
                if (elementType == null)
                {
                    return false;
                }

                return TryMapRepeatedElement(elementType, member, ownerName, out repeatedType);
            }

            private bool TryMapRepeatedElement(
                Type elementType,
                MemberEntry scope,
                string ownerName,
                out string protoType
            )
            {
                if (TryResolveSurrogate(elementType, out Type surrogateType))
                {
                    string surrogateName = TryAddContract(surrogateType);
                    if (surrogateName == null)
                    {
                        protoType = null;
                        return false;
                    }

                    protoType = surrogateName;
                    return true;
                }

                if (elementType.IsEnum)
                {
                    protoType = TryAddEnum(elementType);
                    return protoType != null;
                }

                if (elementType == typeof(byte[]))
                {
                    // A byte[] is a bytes scalar rather than a run of its own, so byte[][] is an
                    // ordinary repeated field, not a wrapper -- the same call the generator makes.
                    protoType = "bytes";
                    return true;
                }

                if (elementType.IsArray || IsCollection(elementType))
                {
                    // A jagged collection has no proto spelling, so each inner run gets the same
                    // wrapper message the source generator synthesizes: a repeated wrapper at the
                    // member tag, the inner run at field one.
                    Type innerElement = GetElementType(elementType);
                    if (innerElement == null)
                    {
                        protoType = null;
                        return false;
                    }

                    string wrapperName = NextName(scope.SchemaName + "Entry");
                    MemberEntry innerScope = new MemberEntry
                    {
                        SchemaName = "values",
                        Tag = 1,
                        MemberType = innerElement,
                    };
                    if (
                        !TryMapRepeatedElement(
                            innerElement,
                            innerScope,
                            ownerName,
                            out string innerType
                        )
                    )
                    {
                        protoType = null;
                        return false;
                    }

                    StringBuilder wrapper = new StringBuilder();
                    wrapper.Append("message ").Append(wrapperName).Append(" {").Append("\n");
                    wrapper
                        .Append("  repeated ")
                        .Append(innerType)
                        .Append(" values = 1;")
                        .Append("\n");
                    wrapper.Append("}");
                    _blocks[MessageKeyPrefix + wrapperName] = wrapper.ToString();
                    protoType = wrapperName;
                    return true;
                }

                if (TryMapScalar(elementType, scope, out protoType))
                {
                    return true;
                }

                return TryMapContract(elementType, out protoType);
            }

            private bool TryMapContract(Type type, out string protoType)
            {
                object[] markers = type.GetCustomAttributes(typeof(WProtoContractAttribute), false);
                if (markers.Length == 0)
                {
                    protoType = null;
                    return false;
                }

                protoType = TryAddContract(type);
                return protoType != null;
            }

            private bool TryBuildRectBody(
                string rectName,
                Type elementType,
                string ownerName,
                out string definition
            )
            {
                MemberEntry elementScope = new MemberEntry
                {
                    SchemaName = "values",
                    Tag = 2,
                    MemberType = elementType,
                };

                if (
                    !TryMapRepeatedElement(
                        elementType,
                        elementScope,
                        ownerName,
                        out string valuesType
                    )
                )
                {
                    definition = null;
                    _diagnostics.Add(
                        $"{ownerName}: rectangular element {elementType.Name} has no supported wire shape; skipped."
                    );
                    return false;
                }

                StringBuilder rect = new StringBuilder();
                rect.Append("message ").Append(rectName).Append(" {").Append("\n");
                rect.Append("  repeated int32 dims = 1;").Append("\n");
                rect.Append("  repeated ").Append(valuesType).Append(" values = 2;").Append("\n");
                rect.Append("}");
                definition = rect.ToString();
                return true;
            }

            private bool TryBuildMap(
                Type memberType,
                MemberEntry member,
                string ownerName,
                out string line
            )
            {
                line = null;
                Type[] arguments = memberType.GetGenericArguments();
                Type keyType = arguments[0];
                Type valueType = arguments[1];

                if (!TryMapElement(keyType, member, out string keyProtoType))
                {
                    _diagnostics.Add(
                        $"{ownerName}.{member.SchemaName}: map key {keyType.Name} has no proto3 spelling; skipped."
                    );
                    return false;
                }

                if (!TryMapElement(valueType, member, out string valueProtoType))
                {
                    _diagnostics.Add(
                        $"{ownerName}.{member.SchemaName}: map value {valueType.Name} has no supported wire shape; skipped."
                    );
                    return false;
                }

                if (IsProto3MapKey(keyProtoType))
                {
                    line = $"map<{keyProtoType}, {valueProtoType}>";
                    return true;
                }

                // proto3 map keys are restricted to integral, boolean and string scalars; the wire
                // form is a repeated entry message either way, so emit exactly that.
                string entryName = NextName(member.SchemaName + "Entry");
                StringBuilder entry = new StringBuilder();
                entry.Append("message ").Append(entryName).Append(" {").Append("\n");
                entry.Append("  ").Append(keyProtoType).Append(" key = 1;").Append("\n");
                entry.Append("  ").Append(valueProtoType).Append(" value = 2;").Append("\n");
                entry.Append("}");
                _blocks[MessageKeyPrefix + entryName] = entry.ToString();
                line = entryName;
                return true;
            }

            private string TryAddEnum(Type enumType)
            {
                string blockKey = EnumKeyPrefix + enumType.Name;
                if (_blocks.ContainsKey(blockKey))
                {
                    return enumType.Name;
                }

                Array values = Enum.GetValues(enumType);
                string[] names = Enum.GetNames(enumType);
                if (values.Length == 0)
                {
                    _diagnostics.Add($"enum {enumType.Name}: declares no members; skipped.");
                    return null;
                }

                bool aliases = false;
                List<KeyValuePair<string, long>> declared = new List<KeyValuePair<string, long>>(
                    values.Length
                );
                HashSet<long> seen = new HashSet<long>();
                for (int i = 0; i < values.Length; ++i)
                {
                    long raw = Convert.ToInt64(values.GetValue(i), CultureInfo.InvariantCulture);
                    if (!seen.Add(raw))
                    {
                        aliases = true;
                    }

                    declared.Add(new KeyValuePair<string, long>(names[i], raw));
                }

                if (declared[0].Value != 0)
                {
                    _diagnostics.Add(
                        $"enum {enumType.Name}: proto3 wants the first member at 0; it opens at {declared[0].Value}."
                    );
                }

                StringBuilder body = new StringBuilder();
                body.Append("enum ").Append(enumType.Name).Append(" {").Append("\n");
                if (aliases)
                {
                    body.Append("  option allow_alias = true;").Append("\n");
                }

                foreach (KeyValuePair<string, long> member in declared)
                {
                    body.Append("  ")
                        .Append(member.Key)
                        .Append(" = ")
                        .Append(member.Value.ToString(CultureInfo.InvariantCulture))
                        .Append(";")
                        .Append("\n");
                }

                body.Append("}");
                string definition = body.ToString();
                _blocks[blockKey] = definition;
                return enumType.Name;
            }

            private List<IncludeEntry> CollectIncludes(Type contractType)
            {
                List<IncludeEntry> includes = new List<IncludeEntry>();
                object[] markers = contractType.GetCustomAttributes(
                    typeof(WProtoIncludeAttribute),
                    false
                );
                foreach (object markerObject in markers)
                {
                    WProtoIncludeAttribute marker = (WProtoIncludeAttribute)markerObject;
                    Type derived = marker.KnownType;
                    if (derived == null)
                    {
                        _diagnostics.Add(
                            $"WProtoInclude at tag {marker.Tag} on {contractType.Name} names no type; skipped."
                        );
                        continue;
                    }

                    string derivedName = NextName(ResolveContractName(derived));
                    // CollectMembers walks the hierarchy, so this is already the subtype's own
                    // members plus everything it inherits -- the exact set the wire carries.
                    List<MemberEntry> derivedMembers = CollectMembers(derived, derivedName);

                    StringBuilder body = new StringBuilder();
                    body.Append("// ")
                        .Append(ResolveContractName(contractType))
                        .Append(" writes this subtype under tag ")
                        .Append(marker.Tag)
                        .Append(": its own members first, then the base's.")
                        .Append("\n");
                    body.Append("message ").Append(derivedName).Append(" {").Append("\n");
                    foreach (MemberEntry member in derivedMembers)
                    {
                        string line = RenderField(derivedName, member);
                        if (line != null)
                        {
                            body.Append("  ").Append(line).Append("\n");
                        }
                    }

                    body.Append("}");
                    _blocks[MessageKeyPrefix + derivedName] = body.ToString();

                    includes.Add(new IncludeEntry { Tag = marker.Tag, SchemaName = derivedName });
                }

                return includes;
            }

            private List<MemberEntry> CollectMembers(Type contractType, string messageName)
            {
                List<MemberEntry> members = new List<MemberEntry>();
                for (
                    Type current = contractType;
                    current != null && current != typeof(object);
                    current = current.BaseType
                )
                {
                    AppendDeclaredMembers(current, messageName, members);
                }

                List<MemberEntry> unique = new List<MemberEntry>(members.Count);
                HashSet<int> seenTags = new HashSet<int>();
                foreach (MemberEntry member in members)
                {
                    if (!seenTags.Add(member.Tag))
                    {
                        continue;
                    }

                    unique.Add(member);
                }

                unique.Sort((left, right) => left.Tag.CompareTo(right.Tag));
                return unique;
            }

            private void AppendDeclaredMembers(
                Type declaredType,
                string messageName,
                List<MemberEntry> into
            )
            {
                IEnumerable<MemberEntry> fields = declaredType
                    .GetFields(MemberSearchFlags)
                    .Select(member => BuildMember(member, messageName))
                    .Where(entry => entry != null);
                IEnumerable<MemberEntry> properties = declaredType
                    .GetProperties(MemberSearchFlags)
                    .Select(member => BuildMember(member, messageName))
                    .Where(entry => entry != null);

                into.AddRange(fields);
                into.AddRange(properties);
            }

            private MemberEntry BuildMember(MemberInfo member, string messageName)
            {
                object[] markers = member.GetCustomAttributes(typeof(WProtoMemberAttribute), false);
                if (markers.Length == 0)
                {
                    return null;
                }

                WProtoMemberAttribute marker = (WProtoMemberAttribute)markers[0];
                Type memberType;
                if (member is FieldInfo field)
                {
                    memberType = field.FieldType;
                }
                else
                {
                    memberType = ((PropertyInfo)member).PropertyType;
                }

                string schemaName = string.IsNullOrEmpty(marker.Name) ? member.Name : marker.Name;
                if (!IsValidProtoIdentifier(schemaName))
                {
                    _diagnostics.Add(
                        $"{messageName}.{schemaName}: not a valid proto3 identifier; renamed to field_{marker.Tag}."
                    );
                    schemaName = "field_" + marker.Tag.ToString(CultureInfo.InvariantCulture);
                }

                return new MemberEntry
                {
                    SchemaName = schemaName,
                    Tag = marker.Tag,
                    MemberType = memberType,
                    DataFormatZigZag = marker.DataFormat == WProtoDataFormat.ZigZag,
                };
            }

            private bool TryResolveSurrogate(Type type, out Type surrogateType)
            {
                return _surrogates.TryGetValue(type, out surrogateType) && surrogateType != null;
            }

            private string SchemaNameOf(Type contractType)
            {
                if (
                    _contractNames.TryGetValue(contractType, out string rendered)
                    && rendered != null
                )
                {
                    return rendered;
                }

                return ResolveContractName(contractType);
            }

            private string ResolveSchemaName(Type type, WProtoContractAttribute marker)
            {
                return string.IsNullOrEmpty(marker.Name) ? ResolveContractName(type) : marker.Name;
            }

            private static string ResolveContractName(Type type)
            {
                object[] markers = type.GetCustomAttributes(typeof(WProtoContractAttribute), false);
                if (markers.Length > 0)
                {
                    string declared = ((WProtoContractAttribute)markers[0]).Name;
                    if (!string.IsNullOrEmpty(declared))
                    {
                        return declared;
                    }
                }

                return type.Name;
            }

            private string NextName(string desired)
            {
                string candidate = desired;
                int suffix = 2;
                while (
                    _usedNames.Contains(candidate)
                    || _blocks.ContainsKey(MessageKeyPrefix + candidate)
                    || _blocks.ContainsKey(EnumKeyPrefix + candidate)
                )
                {
                    candidate = desired + suffix.ToString(CultureInfo.InvariantCulture);
                    ++suffix;
                }

                _usedNames.Add(candidate);
                return candidate;
            }

            public string Render(string packageName)
            {
                StringBuilder schema = new StringBuilder();
                schema.Append(Header);
                if (!string.IsNullOrWhiteSpace(packageName))
                {
                    schema.Append("package ").Append(packageName.Trim()).Append(";").Append("\n");
                }

                schema.Append("\n");
                foreach (
                    KeyValuePair<string, string> block in _blocks.OrderBy(
                        pair => pair.Key,
                        StringComparer.Ordinal
                    )
                )
                {
                    schema.Append(block.Value).Append("\n");
                    schema.Append("\n");
                }

                return schema.ToString();
            }

            private bool TryMapScalar(Type type, MemberEntry member, out string protoType)
            {
                protoType = MapScalarName(type, member);
                return protoType != null;
            }

            private string MapScalarName(Type type, MemberEntry member)
            {
                bool zigZag = member.DataFormatZigZag;
                if (type == typeof(bool))
                {
                    return "bool";
                }

                if (type == typeof(sbyte))
                {
                    return zigZag ? "sint32" : "int32";
                }

                if (type == typeof(short))
                {
                    return zigZag ? "sint32" : "int32";
                }

                if (type == typeof(int))
                {
                    return zigZag ? "sint32" : "int32";
                }

                if (type == typeof(long))
                {
                    return zigZag ? "sint64" : "int64";
                }

                if (type == typeof(byte))
                {
                    return "uint32";
                }

                if (type == typeof(ushort))
                {
                    return "uint32";
                }

                if (type == typeof(uint))
                {
                    return "uint32";
                }

                if (type == typeof(ulong))
                {
                    return "uint64";
                }

                if (type == typeof(char))
                {
                    return "uint32";
                }

                if (type == typeof(float))
                {
                    return "fixed32";
                }

                if (type == typeof(double))
                {
                    return "fixed64";
                }

                if (type == typeof(string))
                {
                    return "string";
                }

                if (BclMessageShapes.TryGetValue(type, out (string MessageName, string _) shape))
                {
                    _blocks[MessageKeyPrefix + shape.MessageName] = BclMessageShapes[
                        type
                    ].Definition;
                    return shape.MessageName;
                }

                return null;
            }

            private bool TryMapElement(Type type, MemberEntry member, out string protoType)
            {
                if (TryResolveSurrogate(type, out Type surrogateType))
                {
                    string surrogateName = TryAddContract(surrogateType);
                    if (surrogateName == null)
                    {
                        protoType = null;
                        return false;
                    }

                    protoType = surrogateName;
                    return true;
                }

                if (type.IsEnum)
                {
                    protoType = TryAddEnum(type);
                    return protoType != null;
                }

                if (TryMapScalar(type, member, out protoType))
                {
                    return true;
                }

                return TryMapContract(type, out protoType);
            }

            private static Type GetElementType(Type type)
            {
                if (type.IsArray)
                {
                    return type.GetElementType();
                }

                if (type.IsGenericType)
                {
                    Type definition = type.GetGenericTypeDefinition();
                    if (definition == typeof(IEnumerable<>))
                    {
                        return type.GetGenericArguments()[0];
                    }
                }

                foreach (Type implemented in type.GetInterfaces())
                {
                    if (
                        implemented.IsGenericType
                        && implemented.GetGenericTypeDefinition() == typeof(IEnumerable<>)
                    )
                    {
                        return implemented.GetGenericArguments()[0];
                    }
                }

                return null;
            }

            private static bool IsCollection(Type type)
            {
                if (type == typeof(string) || type == typeof(byte[]))
                {
                    return false;
                }

                if (
                    type.IsArray
                    || (
                        type.IsGenericType
                        && type.GetGenericTypeDefinition() == typeof(IEnumerable<>)
                    )
                )
                {
                    return true;
                }

                foreach (Type implemented in type.GetInterfaces())
                {
                    if (
                        implemented.IsGenericType
                        && implemented.GetGenericTypeDefinition() == typeof(IEnumerable<>)
                    )
                    {
                        return true;
                    }
                }

                return false;
            }

            private static bool IsMapDictionary(Type type)
            {
                Type definition = type.GetGenericTypeDefinition();
                return definition == typeof(Dictionary<,>)
                    || definition == typeof(IDictionary<,>)
                    || definition == typeof(IReadOnlyDictionary<,>)
                    || definition == typeof(ReadOnlyDictionary<,>);
            }

            private static bool IsProto3MapKey(string protoType)
            {
                switch (protoType)
                {
                    case "bool":
                    case "int32":
                    case "int64":
                    case "uint32":
                    case "uint64":
                    case "sint32":
                    case "sint64":
                    case "fixed32":
                    case "fixed64":
                    case "string":
                        return true;
                    default:
                        return false;
                }
            }

            private static bool IsValidProtoIdentifier(string name)
            {
                if (string.IsNullOrEmpty(name))
                {
                    return false;
                }

                if (!char.IsLetter(name[0]) && name[0] != '_')
                {
                    return false;
                }

                foreach (char character in name)
                {
                    if (!char.IsLetterOrDigit(character) && character != '_')
                    {
                        return false;
                    }
                }

                return true;
            }

            private static string FieldName(string messageName)
            {
                return char.ToLowerInvariant(messageName[0]) + messageName.Substring(1);
            }
        }

        private sealed class IncludeEntry
        {
            public int Tag;
            public string SchemaName;
        }

        private sealed class MemberEntry
        {
            public string SchemaName;
            public int Tag;
            public Type MemberType;
            public bool DataFormatZigZag;
        }
    }
}
